Profile page
BeyondVisionAI/web_application pull request #103
Opened 2022-12-08 00:51 UTC by MinMatth-Magi

2022-12-08 06:54 UTC, Dimitri-CLAIN requested changes

2022-12-08 06:54 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/Lists/Lists.jsx
> +                <div style={{ marginRight:'1vw', marginTop:'2vh' }}><AccountButton /></div>
Le AccountButton est dispo dans l'éditeur, dans la page projects ?

2022-12-08 13:23 UTC, MinMatth-Magi commented on Frontend/src/Pages/Lists/Lists.jsx
> +                <div style={{ marginRight:'1vw', marginTop:'2vh' }}><AccountButton /></div>
Dispo oui, implémenté non

2022-12-17 08:39 UTC, Polipoppy approved these changes

2022-12-17 20:33 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/Lists/Lists.jsx
> +                <div style={{ marginRight:'1vw', marginTop:'2vh' }}><AccountButton /></div>
Pour quoi tu l'implémente pas du coup ?

2022-12-17 20:36 UTC, Dimitri-CLAIN commented
T'a update la landing page ?

2022-12-27 23:09 UTC, Dimitri-CLAIN commented
Sur la page http://localhost/projects le logo account n'est pas present.

2022-12-27 23:14 UTC, Dimitri-CLAIN commented
Sur le Figma on demande ça 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/47006656/209735382-dfeb67ec-56c3-48a4-b5ce-5b1a87d1ed08.png">
mais t'as fait ça (les bords ne sont pas arrondi)
<img width="653" alt="image" src="https://user-images.githubusercontent.com/47006656/209735412-6929bd52-f8b1-4bb4-89a7-f334f3b0b01a.png">
Pourquoi ce choix ?

2022-12-30 17:19 UTC, Polipoppy approved these changes

2023-01-17 20:06 UTC, merged