adding socket on generation and download buttons on editor
BeyondVisionAI/web_application pull request #144
Opened 2023-01-22 20:47 UTC by Marc-olivierLAURET

2023-01-23 21:26 UTC, Dimitri-CLAIN requested changes

2023-01-23 21:26 UTC, Dimitri-CLAIN commented on Backend/Controllers/Project/Project.js
> +            await project.save()
Faire un Await et mettre un then c'est completement inutile.
Await comme then permet d'attendre une promise, c'est soit l'un soit l'autre.

2023-01-23 21:26 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +            generationStatus = generationStatus.generationStatus
"generationStatus = generationStatus.generationStatus" ...
Tu ne peux pas juste passer la generationStatus directement au lieu de faire ça ???

2023-01-23 21:26 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +            updateGenerationButtons({generationStatus});
```suggestion
            updateGenerationButtons(generationStatus);
```
Explique moi l'utilité des {} stp

2023-01-23 21:26 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +            toast.warning(tWarn("generationStart"))
```suggestion
            toast.warning(tWarn("generationStart"));
```

2023-01-23 21:26 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +                            <ImageButton disabled={ replicas.length !== 0 && isEmptyRepliquas() && project.status !== 'InProgress' ? (false) : (true) } type="SendArrow" size='30px' onClick={ () => La
Tu peux mettre "replicas.length !== 0" dans la function directement, non ?

2023-01-27 20:48 UTC, Dimitri-CLAIN requested changes
T'es sur que ça fonctionne ??

2023-01-27 20:48 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +                toast.success(tSuc('scriptEdition.ADGenerationSuccess'))
```suggestion
                toast.success(tSuc('scriptEdition.ADGenerationSuccess'));
```

2023-01-27 20:48 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +    [project]
```suggestion
    }, [project]
```

2023-01-27 20:48 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +        })
```suggestion
        socket.on('update generation status', async({ generationStatus }) => {
            updateGenerationButtons(generationStatus);
        });
```

2023-01-27 20:48 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +            return (false)
```suggestion
            return (false);
```

2023-01-27 21:51 UTC, Dimitri-CLAIN commented on Backend/Controllers/Project/Project.js
> +                sendDataToUser(user, "update generation status", {actualStep:project.actualStep, status: project.status});
```suggestion
                sendDataToUser(user, "update generation status", { actualStep: project.actualStep, status: project.status });
```

2023-01-27 21:53 UTC, Dimitri-CLAIN approved these changes

2023-01-29 19:09 UTC, Fistoflex approved these changes

2023-01-30 09:21 UTC, merged