39 fix la route de retour vers la web app après détection dactions sur le server ia
BeyondVisionAI/web_application pull request #92
Opened 2022-12-01 20:13 UTC by Fistoflex

2022-12-02 17:00 UTC, Fistoflex commented on Backend/Models/Errors.js
>  exports.Errors = Errors;
```suggestion
exports.Errors = Errors;

```

2022-12-02 17:00 UTC, Fistoflex commented on Backend/routes/Project.js
> +
```suggestion

```

2022-12-02 17:00 UTC, Fistoflex commented on Backend/routes/ScriptEdition.js
>  }
```suggestion
}

```

2022-12-02 17:12 UTC, XelaG commented on Backend/Controllers/Project/Project.js
> +                console.log("Project-> IA: ");
Du debug ?

2022-12-02 17:12 UTC, XelaG commented on Backend/Controllers/Project/Project.js
> +                });
Tu as pas d'auth sur le server IA ?

2022-12-02 17:12 UTC, XelaG commented on Backend/Controllers/ScriptEdition/Replica.js
> +        if (!projectId || !content || !voiceId || !actualStep || !status || !lastEditor) {
Tu vérifie pas timestamp et duration, c'est normal ?

2022-12-02 17:12 UTC, XelaG commented on Backend/Controllers/ScriptEdition/Replica.js
> +        newReplica.audioName = `${newReplica.projectId}/${newReplica._id}.mp3`;
Le nom avec un / ça marche j'ai peur que ça fasse bugger des trucs en mode c'est un dossier ou truc dans le genre. Peut etre mettre un - pour que ce soit plus safe ?

2022-12-02 17:12 UTC, XelaG commented on Backend/Controllers/ScriptEdition/Replica.js
> +        if (!projectId || !actionsJson || !userId)
Dans un soucis d'optimisation, ce serait mieux de check avant de commencer a process la donnée (JSON.parse)

2022-12-02 17:12 UTC, XelaG commented on Backend/routes/ScriptEdition.js
> +        //TODO : a implementer
Pas fait ?

2022-12-02 19:13 UTC, Dimitri-CLAIN requested changes

2022-12-02 19:13 UTC, Dimitri-CLAIN commented on Backend/Controllers/ScriptEdition/Replica.js
> +        res.status(200).send("Replica created !");
Pour quoi mettre un message ?
Le retour de la réplica est plus interessante

2022-12-02 19:13 UTC, Dimitri-CLAIN commented on Backend/Controllers/ScriptEdition/Replica.js
> +};
Le 'getReplicaAudioUrl' juste au dessus prend un url qui est désormais save dans la replica, homogénéise :}

2022-12-02 19:13 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/Project/Create/CreateProject.jsx
> -            await axios.post(`${process.env.REACT_APP_API_URL}/projects/${projectResponse.data._id}/generationIA`, { typeGeneration: 'ActionRetrieve' });
??? pour quoi le delete

2022-12-02 19:13 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/ScriptEdition.jsx
> +                            <button
Ou est le tailwind ?

2022-12-08 06:57 UTC, Dimitri-CLAIN approved these changes

2022-12-17 08:37 UTC, Polipoppy requested changes

2022-12-17 08:37 UTC, Polipoppy commented on Backend/Controllers/Project/Project.js
> +                console.log("Project-> IA: ");
console.log :(

2022-12-17 08:37 UTC, Polipoppy commented on Backend/Controllers/Project/Project.js
> +                await axios.post(`${process.env.SERVER_IA_URL}/AI/FaceRecognition/sNewProcess`, { projectId: req.params.projectId });
Normal ce nom de route `sNewProcess` ?

2022-12-27 23:36 UTC, Dimitri-CLAIN requested changes

2022-12-27 23:36 UTC, Dimitri-CLAIN commented on .env
> +SERVER_IA_URL=https://localhost:8082
Ne push pas les modifications que tu fait sur les .env stp.
Cette modification est inutile, et dans le cas où il y a un changement significatif tu peux casser le travail de quelqu'un d'autre.
Pas tout le monde à l'habitude de debug le web, ça peux faire perdre beaucoup de temps

2022-12-27 23:36 UTC, Dimitri-CLAIN commented on Backend/Controllers/Project/Project.js
> +                    jsonPath: "../Files/Json/Action-638a321f6826a6c3cf094b96.json",
Pas moyen de mettre un nom different Action-Exemple.json...

2022-12-27 23:36 UTC, Dimitri-CLAIN commented on Backend/Controllers/Project/Project.js
> +            } if (req.body.typeGeneration === 'ActionRetrieveFake') {
C'est un `else if` que tu veux ?

2022-12-27 23:36 UTC, Dimitri-CLAIN commented on Backend/Controllers/Project/Project.js
> +            } if (req.body.typeGeneration === 'ActionRetrieveFake') {
Il y a pas moyen de mettre un switch case au lieux des if ?

2022-12-27 23:36 UTC, Dimitri-CLAIN commented on Backend/Controllers/Project/Project.js
> +                    jsonPath: "../Files/Json/Action-638a321f6826a6c3cf094b96.json",
J'ai pas le fait d'envoyer le jsonPath, il est pas modulable et dans ton les cas le client n'à pas conscience des files existant dans l'ïa.
Tu peux mettre une variable d'env JSON_ACTION_EXEMPLE qui est justement le path en question.

2022-12-30 20:30 UTC, Fistoflex commented on Backend/Controllers/Project/Project.js
> +                    jsonPath: "../Files/Json/Action-638a321f6826a6c3cf094b96.json",
noted

2022-12-30 20:32 UTC, Fistoflex commented on Backend/Controllers/Project/Project.js
> +            } if (req.body.typeGeneration === 'ActionRetrieveFake') {
```suggestion
            } else if (req.body.typeGeneration === 'ActionRetrieveFake') {
```

2022-12-30 20:40 UTC, Fistoflex commented on Backend/Controllers/Project/Project.js
> +                    jsonPath: "../Files/Json/Action-638a321f6826a6c3cf094b96.json",
je le fais dqns une autre pr :*

2022-12-30 20:41 UTC, Fistoflex commented on Backend/Controllers/Project/Project.js
> +            } if (req.body.typeGeneration === 'ActionRetrieveFake') {
sueur

2022-12-30 20:41 UTC, merged