54 Récupérer la liste des voix sur le serveur IA
BeyondVisionAI/web_application pull request #93
Opened 2022-12-03 13:55 UTC by softhy85

"54 branch temporaire" car pb lors de la création de la branch 54 Récupérer la liste des voix sur le serveur IA avec la dev.

2022-12-03 14:30 UTC, Dimitri-CLAIN requested changes

2022-12-03 14:30 UTC, Dimitri-CLAIN commented on .env
> +SERVER_IA_URL="https://localhost:8082"
Change pas le .env pour tout le monde
```suggestion
SERVER_IA_URL="http://172.17.0.1:8082"
```

2022-12-03 14:30 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/ScriptEdition/Components/ReplicaDetails.jsx
> +                <VoiceChoices voiceId={ voiceIdSelected} setVoiceIdSelected={setVoiceIdSelected} replicaId={replicaId}/>
```suggestion
                <VoiceChoices voiceId={ voiceIdSelected } setVoiceIdSelected={ setVoiceIdSelected } replicaId={ replicaId }/>
```

2022-12-03 15:24 UTC, Fistoflex approved these changes

2022-12-03 15:24 UTC, Fistoflex commented on .env
> +SERVER_IA_URL="https://localhost:8082"
peka

2022-12-03 15:24 UTC, Fistoflex commented on Frontend/src/Pages/ScriptEdition/Components/ReplicaDetails.jsx
```suggestion
```

2022-12-03 15:24 UTC, Fistoflex commented on Frontend/src/Pages/ScriptEdition/Components/ReplicaDetails.jsx
>  export default ReplicaDetails;
```suggestion
export default ReplicaDetails;

```

2022-12-03 15:24 UTC, Fistoflex commented on Frontend/src/Pages/ScriptEdition/Components/VoicesChoice.jsx
> +                    onChange={handleLanguageChange}>
On peut pas mettre le setter ici direct ?

2022-12-03 15:24 UTC, Fistoflex commented on Frontend/src/Pages/ScriptEdition/Components/VoicesChoice.jsx
> +export default VoiceChoices;
```suggestion
export default VoiceChoices;

```

2022-12-03 16:50 UTC, softhy85 commented on Frontend/src/Pages/ScriptEdition/Components/VoicesChoice.jsx
> +                    onChange={handleLanguageChange}>
quand je le mettait le setter le e.target.value n'était pas bon, me demande pas pk en copiant comment était utilisé select avec React sur internet ca a fonctionné, duccoup mnt, j'utilise une fonction handle. Js / React c'est pas intuitif.

2022-12-04 14:02 UTC, Fistoflex approved these changes

2022-12-04 14:02 UTC, Fistoflex commented on Frontend/src/Pages/ScriptEdition/Components/VoicesChoice.jsx
> +                    onChange={handleLanguageChange}>
Oh ok

2022-12-04 16:55 UTC, softhy85 commented on Frontend/src/Pages/ScriptEdition/Components/VoicesChoice.jsx
> +        if (arr !== undefined && arr.length > 0) {
Je le fais <3

2022-12-04 16:56 UTC, softhy85 commented on Frontend/src/Pages/ScriptEdition/Components/ReplicaDetails.jsx
> +                <textarea name="replica-text" id=""
J'ai pas compris le 218 219 220 ? pk supp ca ? C'est meme pas moi qui est fait ca...

2022-12-04 16:57 UTC, softhy85 commented on Frontend/src/Pages/ScriptEdition/Components/VoicesChoice.jsx
> +export default VoiceChoices;
j'ai pas compris la modif

2022-12-04 16:58 UTC, softhy85 commented on Frontend/src/Pages/ScriptEdition/Components/ReplicaDetails.jsx
>  export default ReplicaDetails;
j'ai pas de ligne 322 dans replica detail ? wtf il finis a 244 xD

2022-12-05 21:16 UTC, merged