53 add indicator on project view to see the state of the process generating script with ai generation done
BeyondVisionAI/web_application pull request #98
Opened 2022-12-06 04:39 UTC by softhy85

Pull request crée pour avoir vos avis sur le visuel plus que sur le code (même si je serais heureux d'entendre vos remarques).

Ajout de logo pour chaque Status + Step.
Gestion de logo SVG dans générique component ou l'on peut en ajouté d'autre.

2022-12-07 14:00 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/Lists/Components/ProjectMiniature/ProjectMiniature.jsx
> +    const stepImage = () => {
Tu l'utilise pas cette fonction ?

2022-12-07 14:00 UTC, Dimitri-CLAIN commented on Frontend/src/GenericComponents/SVGLogos/SVGLogos.js
> +        image: <svg xmlns="http://www.w3.org/2000/svg" className="m-auto h-14 w-14" fill="none" viewBox="0 0 26 26" stroke="#868EBB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
En react vos mieux utiliser strokeWidth au lieu de strokeWidth. A verifier dans les autres SVG
```suggestion
        image: <svg xmlns="http://www.w3.org/2000/svg" className="m-auto h-14 w-14" fill="none" viewBox="0 0 26 26" stroke="#868EBB" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
```

2022-12-07 14:00 UTC, Dimitri-CLAIN commented on Frontend/src/GenericComponents/SVGLogos/SVGLogos.js
> +    }
```suggestion
    const logo = logosImages.find(logo => logo === logoType)?.image
```

2022-12-07 14:00 UTC, Dimitri-CLAIN commented on Frontend/src/Pages/Lists/Components/ProjectMiniature/ProjectMiniature.jsx
>              {/* <img className="object-fill w-full h-full" src={`./assets/movies/animal.jpg`} alt={`Movie ${movie.name}`}></img> */}
Je pense que tu peu delete les commentaires 👍

2022-12-07 14:22 UTC, softhy85 commented on Frontend/src/Pages/Lists/Components/ProjectMiniature/ProjectMiniature.jsx
>              {/* <img className="object-fill w-full h-full" src={`./assets/movies/animal.jpg`} alt={`Movie ${movie.name}`}></img> */}
Ok

2022-12-07 14:23 UTC, softhy85 commented on Frontend/src/Pages/Lists/Components/ProjectMiniature/ProjectMiniature.jsx
>              {/* <img className="object-fill w-full h-full" src={`./assets/movies/animal.jpg`} alt={`Movie ${movie.name}`}></img> */}
Mais la partie collaborateur ne sera pas remis ?

2022-12-07 14:24 UTC, softhy85 commented on Frontend/src/Pages/Lists/Components/ProjectMiniature/ProjectMiniature.jsx
> +    const stepImage = () => {
je modifie ca

2022-12-07 14:48 UTC, Dimitri-CLAIN requested changes

2022-12-07 14:48 UTC, Dimitri-CLAIN commented on Frontend/src/GenericComponents/SVGLogos/SVGLogos.js
> +        image: <svg xmlns="http://www.w3.org/2000/svg" className="m-auto h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="#868EBB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
stroke-width -> strokeWidth
stroke-linecap -> strokeLinecap
stroke-linejoin -> strokeLinejoin
**Pareil plus bas**

2022-12-07 15:10 UTC, softhy85 commented on Frontend/src/GenericComponents/SVGLogos/SVGLogos.js
> +        image: <svg xmlns="http://www.w3.org/2000/svg" className="m-auto h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="#868EBB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
Sry, j'ai resolve et oublier :/ Normalement c'est fait mnt

2022-12-17 08:29 UTC, Polipoppy approved these changes

2022-12-17 20:52 UTC, Dimitri-CLAIN approved these changes

2022-12-18 14:56 UTC, merged